# Generated by Django 5.2 on 2025-05-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_email_verified_customuser_is_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_creator',
            field=models.BooleanField(default=True),
        ),
    ]
