# Generated by Django 5.2 on 2025-05-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_creatorprofile_projectprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='category_of_work',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='projectprofile',
            name='talents_needed',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
