# Generated by Django 5.2 on 2025-05-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_creatorprofile_category_of_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='cover_pics',
            field=models.ImageField(default='avatar.png', upload_to='coverImage/'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='profile_picture',
            field=models.ImageField(default='avatar.png', upload_to='profileImages/'),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='cover_pics',
            field=models.ImageField(default='avatar.png', upload_to='coverProject/'),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='profile_picture',
            field=models.ImageField(default='avatar.png', upload_to='projectImages/'),
        ),
    ]
